# Generated by Django 3.0.4 on 2020-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='An interesting participator in Developer Stories'),
        ),
    ]
