# Generated by Django 3.0.4 on 2020-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_story_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_published',
        ),
        migrations.AddField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
