# Generated by Django 3.0.4 on 2020-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_saveforlater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveforlater',
            old_name='key',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='saveforlater',
            name='is_saved',
        ),
        migrations.AddField(
            model_name='story',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
