# Generated by Django 3.0.4 on 2020-09-26 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0018_auto_20200910_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoryNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='portal.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
