# Generated by Django 3.0.4 on 2021-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200926_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], default='OFFLINE', max_length=10),
        ),
    ]
