# Generated by Django 3.0.4 on 2021-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_userprofile_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='online_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
